name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the Streamlit app URL
        run: curl -sS "https://iracalculator.streamlit.app/"
