name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */4 * * *"

  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the Streamlit app URL
        run: |
          curl -sS -L \
          -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
          -c cookie-jar.txt -b cookie-jar.txt \
          "https://iracalculator.streamlit.app/"
